 ---
apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlpHRjJhV1F4TVdGc2IyNXpienBFWVdOaGFuVXlNREl4IgoJCX0KCX0KfQ==
kind: Secret
metadata:
  name: regcred
  namespace: default
  resourceVersion: "18613916"
  selfLink: /api/v1/namespaces/default/secrets/regcred
  uid: f698b586-5d53-4c76-b386-f925797758a9
type: Opaque

 ---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: private-reg-container
        image: prograavanzadaweb/backend:latest
      imagePullSecrets:
      - name: regcred

 ---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: backend-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: backend
  sessionAffinity: None



