 ---
apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlpHRjJhV1F4TVdGc2IyNXpienBFWVdOaGFuVXlNREl4IgoJCX0KCX0KfQ==
kind: Secret
metadata:
  name: regcred
  namespace: default
  resourceVersion: "18613916"
  selfLink: /api/v1/namespaces/default/secrets/regcred
  uid: f698b586-5d53-4c76-b386-f925797758a9
type: Opaque